/**
 * Created by shinest on 10/01/2017.
 */
// ui action
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE= 'HIDE_ERROR_MESSAGE';


// frontend action
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';
export const GET_ABOUT_SUCCESS = 'GET_ABOUT_SUCCESS';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_COUNT_SUCCESS = 'GET_CATEGORIES_COUNT_SUCCESS';



export const FAIL = 'FAIL';


// backend action
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM'
export const CHANGE_POST_FORM = 'CHANGE_POST_FORM'
export const SET_AUTH = 'SET_AUTH';
export const GET_BACKEND_POST_LIST_SUCCESS = 'GET_BACKEND_POST_LIST_SUCCESS';
export const GET_BACKEND_EDIT_POST_SUCCESS = 'GET_BACKEND_EDIT_POST_SUCCESS';
